"""add email notification tracking

Revision ID: 4864c8652cd5
Revises: f9a573ecef3a
Create Date: 2026-09-25 15:49:32.929877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4864c8652cd5'
down_revision: Union[str, Sequence[str], None] = 'f9a573ecef3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('email_sent', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'email_sent_at')
    op.drop_column('notifications', 'email_sent')
    # ### end Alembic commands ###
